exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

collections:
  agencies:
    output: true
    permalink: /:path/
  data_pages:
    output: true
    permalink: /:path/data/

# Site title and description
title: "webanalytics.gov.je | The Government of Jersey's web traffic."
description: "Official data on web traffic to the States of Jersey government websites."

# Site's own URL
url: http://webanalytics.gov.je

# Default dropdown title, will not appear if there are no sub-pages
dropdown_title: All Participating Websites

# Default data url
data_url: https://s3-eu-west-1.amazonaws.com/sojdata/live

# GitHub information
org_name: StatesOfJersey
repo_name: webanalytics.gov.je

# twitter information
twitter: statesofjersey

sass:
  sass_dir: sass
  style: nested
